name: CI - App Client

on:
  pull_request:
    paths:
      - 'packages/app-client/**'
      - 'packages/lib/**'
      - 'packages/crypto/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
      - '.github/workflows/ci-app-client.yaml'
      - '.github/actions/pnpm-setup/**'
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-app-client-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci-app-client:
    name: CI - App Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/app-client

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Setup Node + pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Run linters
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Run unit test
        run: pnpm test

      - name: Build the app
        run: pnpm build
